		{ "read", 3, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "write", 3, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "open", 3, { Long, 8 }, { { Pointer, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "close", 1, { Long, 8 }, { { UInt, 4 } } },
		{ "stat", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "fstat", 2, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 } } },
		{ "lstat", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "poll", 3, { Long, 8 }, { { Pointer, 8 }, { UInt, 4 }, { Int, 4 } } },
		{ "lseek", 3, { Long, 8 }, { { UInt, 4 }, { Typedef, 8 }, { UInt, 4 } } },
		{ "mmap", 6, { Pointer, 8 }, { { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "mprotect", 3, { Long, 8 }, { { ULong, 8 }, { Int, 4 }, { ULong, 8 } } },
		{ "munmap", 2, { Long, 8 }, { { ULong, 8 }, { Int, 4 } } },
		{ "brk", 1, { Pointer, 8 }, { { ULong, 8 } } },
		{ "rt_sigaction", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "rt_sigprocmask", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "rt_sigreturn", 0, { Long, 8 }, { } },
		{ "ioctl", 3, { Long, 8 }, { { UInt, 4 }, { UInt, 4 }, { ULong, 8 } } },
		{ "pread64", 4, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 }, { Int, 4 }, { Typedef, 8 } } },
		{ "pwrite64", 4, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 }, { Int, 4 }, { Typedef, 8 } } },
		{ "readv", 3, { Long, 8 }, { { ULong, 8 }, { Pointer, 8 }, { ULong, 8 } } },
		{ "writev", 3, { Long, 8 }, { { ULong, 8 }, { Pointer, 8 }, { ULong, 8 } } },
		{ "access", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "pipe", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "select", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "sched_yield", 0, { Long, 8 }, { } },
		{ "mremap", 2, { Pointer, 8 }, { { ULong, 8 }, { ULong, 8 } } },
		{ "msync", 3, { Long, 8 }, { { ULong, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "mincore", 3, { Long, 8 }, { { ULong, 8 }, { Int, 4 }, { Pointer, 8 } } },
		{ "madvise", 3, { Long, 8 }, { { ULong, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "shmget", 3, { Long, 8 }, { { Typedef, 4 }, { Int, 4 }, { Int, 4 } } },
		{ "shmat", 3, { Pointer, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "shmctl", 3, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Pointer, 8 } } },
		{ "dup", 1, { Long, 8 }, { { UInt, 4 } } },
		{ "dup2", 2, { Long, 8 }, { { UInt, 4 }, { UInt, 4 } } },
		{ "pause", 0, { Long, 8 }, { } },
		{ "nanosleep", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "getitimer", 2, { Long, 8 }, { { Int, 4 }, { Pointer, 8 } } },
		{ "alarm", 1, { Long, 8 }, { { UInt, 4 } } },
		{ "setitimer", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "getpid", 0, { Long, 8 }, { } },
		{ "sendfile", 4, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "socket", 3, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Int, 4 } } },
		{ "connect", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "accept", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "sendto", 6, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { UInt, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "recvfrom", 6, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { UInt, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "sendmsg", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "recvmsg", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "shutdown", 2, { Long, 8 }, { { Int, 4 }, { Int, 4 } } },
		{ "bind", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "listen", 2, { Long, 8 }, { { Int, 4 }, { Int, 4 } } },
		{ "getsockname", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "getpeername", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "socketpair", 4, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Int, 4 }, { Pointer, 8 } } },
		{ "setsockopt", 5, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "getsockopt", 5, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "clone", 2, { Long, 8 }, { { ULong, 8 }, { ULong, 8 } } },
		{ "fork", 0, { Long, 8 }, { } },
		{ "vfork", 0, { Long, 8 }, { } },
		{ "execve", 3, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "exit", 1, { Long, 8 }, { { Int, 4 } } },
		{ "wait4", 4, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 }, { Int, 4 }, { Pointer, 8 } } },
		{ "kill", 2, { Long, 8 }, { { Typedef, 4 }, { Int, 4 } } },
		{ "uname", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "semget", 3, { Long, 8 }, { { Typedef, 4 }, { Int, 4 }, { Int, 4 } } },
		{ "semop", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "semctl", 4, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Int, 4 }, { ULong, 8 } } },
		{ "shmdt", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "msgget", 2, { Long, 8 }, { { Typedef, 4 }, { Int, 4 } } },
		{ "msgsnd", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "msgrcv", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Long, 8 }, { Int, 4 } } },
		{ "msgctl", 3, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Pointer, 8 } } },
		{ "fcntl", 3, { Long, 8 }, { { UInt, 4 }, { UInt, 4 }, { ULong, 8 } } },
		{ "flock", 2, { Long, 8 }, { { UInt, 4 }, { UInt, 4 } } },
		{ "fsync", 1, { Long, 8 }, { { UInt, 4 } } },
		{ "fdatasync", 1, { Long, 8 }, { { UInt, 4 } } },
		{ "truncate", 2, { Long, 8 }, { { Pointer, 8 }, { Long, 8 } } },
		{ "ftruncate", 2, { Long, 8 }, { { UInt, 4 }, { Typedef, 8 } } },
		{ "getdents", 3, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "getcwd", 2, { Long, 8 }, { { Pointer, 8 }, { ULong, 8 } } },
		{ "chdir", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "fchdir", 1, { Long, 8 }, { { UInt, 4 } } },
		{ "rename", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "mkdir", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "rmdir", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "creat", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "link", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "unlink", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "symlink", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "readlink", 3, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "chmod", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "fchmod", 2, { Long, 8 }, { { UInt, 4 }, { Int, 4 } } },
		{ "chown", 3, { Long, 8 }, { { Pointer, 8 }, { Typedef, 4 }, { Typedef, 4 } } },
		{ "fchown", 3, { Long, 8 }, { { UInt, 4 }, { Typedef, 4 }, { Typedef, 4 } } },
		{ "lchown", 3, { Long, 8 }, { { Pointer, 8 }, { Typedef, 4 }, { Typedef, 4 } } },
		{ "umask", 1, { Long, 8 }, { { Int, 4 } } },
		{ "gettimeofday", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "getrlimit", 2, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 } } },
		{ "getrusage", 2, { Long, 8 }, { { Int, 4 }, { Pointer, 8 } } },
		{ "sysinfo", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "times", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "ptrace", 4, { Long, 8 }, { { Long, 8 }, { Long, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "getuid", 0, { Long, 8 }, { } },
		{ "syslog", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "getgid", 0, { Long, 8 }, { } },
		{ "setuid", 1, { Long, 8 }, { { Typedef, 4 } } },
		{ "setgid", 1, { Long, 8 }, { { Typedef, 4 } } },
		{ "geteuid", 0, { Long, 8 }, { } },
		{ "getegid", 0, { Long, 8 }, { } },
		{ "setpgid", 2, { Long, 8 }, { { Typedef, 4 }, { Typedef, 4 } } },
		{ "getppid", 0, { Long, 8 }, { } },
		{ "getpgrp", 0, { Long, 8 }, { } },
		{ "setsid", 0, { Long, 8 }, { } },
		{ "setreuid", 2, { Long, 8 }, { { Typedef, 4 }, { Typedef, 4 } } },
		{ "setregid", 2, { Long, 8 }, { { Typedef, 4 }, { Typedef, 4 } } },
		{ "getgroups", 2, { Long, 8 }, { { Int, 4 }, { Pointer, 8 } } },
		{ "setgroups", 2, { Long, 8 }, { { Int, 4 }, { Pointer, 8 } } },
		{ "setresuid", 3, { Long, 8 }, { { Typedef, 4 }, { Typedef, 4 }, { Typedef, 4 } } },
		{ "getresuid", 3, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "setresgid", 3, { Long, 8 }, { { Typedef, 4 }, { Typedef, 4 }, { Typedef, 4 } } },
		{ "getresgid", 3, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "getpgid", 1, { Long, 8 }, { { Typedef, 4 } } },
		{ "setfsuid", 1, { Long, 8 }, { { Typedef, 4 } } },
		{ "setfsgid", 1, { Long, 8 }, { { Typedef, 4 } } },
		{ "getsid", 1, { Long, 8 }, { { Typedef, 4 } } },
		{ "capget", 2, { Long, 8 }, { { Int, 4 }, { Int, 4 } } },
		{ "capset", 2, { Long, 8 }, { { Int, 4 }, { Int, 4 } } },
		{ "rt_sigpending", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "rt_sigtimedwait", 4, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "rt_sigqueueinfo", 3, { Long, 8 }, { { Typedef, 4 }, { Int, 4 }, { Pointer, 8 } } },
		{ "rt_sigsuspend", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "sigaltstack", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "utime", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "mknod", 3, { Long, 8 }, { { Pointer, 8 }, { Int, 4 }, { UInt, 4 } } },
		{ "uselib", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "personality", 1, { Long, 8 }, { { UInt, 4 } } },
		{ "ustat", 2, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 } } },
		{ "statfs", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "fstatfs", 2, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 } } },
		{ "sysfs", 3, { Long, 8 }, { { Int, 4 }, { ULong, 8 }, { ULong, 8 } } },
		{ "getpriority", 2, { Long, 8 }, { { Int, 4 }, { Int, 4 } } },
		{ "setpriority", 3, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Int, 4 } } },
		{ "sched_setparam", 2, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 } } },
		{ "sched_getparam", 2, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 } } },
		{ "sched_setscheduler", 3, { Long, 8 }, { { Typedef, 4 }, { Int, 4 }, { Pointer, 8 } } },
		{ "sched_getscheduler", 1, { Long, 8 }, { { Typedef, 4 } } },
		{ "sched_get_priority_max", 1, { Long, 8 }, { { Int, 4 } } },
		{ "sched_get_priority_min", 1, { Long, 8 }, { { Int, 4 } } },
		{ "sched_rr_get_interval", 2, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 } } },
		{ "mlock", 2, { Long, 8 }, { { ULong, 8 }, { Int, 4 } } },
		{ "munlock", 2, { Long, 8 }, { { ULong, 8 }, { Int, 4 } } },
		{ "mlockall", 1, { Long, 8 }, { { Int, 4 } } },
		{ "munlockall", 0, { Long, 8 }, { } },
		{ "vhangup", 0, { Long, 8 }, { } },
		{ "modify_ldt", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { ULong, 8 } } },
		{ "pivot_root", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "_sysctl", 0, { Long, 8 }, { } },
		{ "prctl", 5, { Long, 8 }, { { Int, 4 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "arch_prctl", 2, { Long, 8 }, { { Int, 4 }, { ULong, 8 } } },
		{ "adjtimex", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "setrlimit", 2, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 } } },
		{ "chroot", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "sync", 0, { Long, 8 }, { } },
		{ "acct", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "settimeofday", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "mount", 5, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { ULong, 8 }, { Pointer, 8 } } },
		{ "umount2", 0, { Long, 8 }, { } },
		{ "swapon", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "swapoff", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "reboot", 4, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { UInt, 4 }, { Pointer, 8 } } },
		{ "sethostname", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "setdomainname", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "iopl", 1, { Long, 8 }, { { UInt, 4 } } },
		{ "ioperm", 3, { Long, 8 }, { { ULong, 8 }, { ULong, 8 }, { Int, 4 } } },
		{ "create_module", 0, { Long, 8 }, { } },
		{ "init_module", 3, { Long, 8 }, { { Pointer, 8 }, { ULong, 8 }, { Pointer, 8 } } },
		{ "delete_module", 2, { Long, 8 }, { { Pointer, 8 }, { UInt, 4 } } },
		{ "get_kernel_syms", 0, { Long, 8 }, { } },
		{ "query_module", 0, { Long, 8 }, { } },
		{ "quotactl", 4, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 }, { Int, 4 }, { Pointer, 8 } } },
		{ "nfsservctl", 0, { Long, 8 }, { } },
		{ "getpmsg", 0, { Long, 8 }, { } },
		{ "putpmsg", 0, { Long, 8 }, { } },
		{ "afs_syscall", 0, { Long, 8 }, { } },
		{ "tuxcall", 0, { Long, 8 }, { } },
		{ "security", 0, { Long, 8 }, { } },
		{ "gettid", 0, { Long, 8 }, { } },
		{ "readahead", 3, { Long, 8 }, { { Int, 4 }, { Typedef, 8 }, { Int, 4 } } },
		{ "setxattr", 5, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "lsetxattr", 5, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "fsetxattr", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "getxattr", 4, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "lgetxattr", 4, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "fgetxattr", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "listxattr", 3, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "llistxattr", 3, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "flistxattr", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "removexattr", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "lremovexattr", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "fremovexattr", 2, { Long, 8 }, { { Int, 4 }, { Pointer, 8 } } },
		{ "tkill", 2, { Long, 8 }, { { Typedef, 4 }, { Int, 4 } } },
		{ "time", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "futex", 6, { Long, 8 }, { { Pointer, 8 }, { Int, 4 }, { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "sched_setaffinity", 3, { Long, 8 }, { { Typedef, 4 }, { UInt, 4 }, { Pointer, 8 } } },
		{ "sched_getaffinity", 3, { Long, 8 }, { { Typedef, 4 }, { UInt, 4 }, { Pointer, 8 } } },
		{ "set_thread_area", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "io_setup", 2, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 } } },
		{ "io_destroy", 1, { Long, 8 }, { { Int, 4 } } },
		{ "io_getevents", 5, { Long, 8 }, { { Int, 4 }, { Long, 8 }, { Long, 8 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "io_submit", 3, { Long, 8 }, { { Int, 4 }, { Long, 8 }, { Pointer, 8 } } },
		{ "io_cancel", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "get_thread_area", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "lookup_dcookie", 0, { Long, 8 }, { } },
		{ "epoll_create", 1, { Long, 8 }, { { Int, 4 } } },
		{ "epoll_ctl_old", 0, { Long, 8 }, { } },
		{ "epoll_wait_old", 0, { Long, 8 }, { } },
		{ "remap_file_pages", 5, { Long, 8 }, { { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "getdents64", 3, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "set_tid_address", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "restart_syscall", 0, { Long, 8 }, { } },
		{ "semtimedop", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 }, { Pointer, 8 } } },
		{ "fadvise64", 4, { Long, 8 }, { { Int, 4 }, { Typedef, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "timer_create", 3, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "timer_settime", 4, { Long, 8 }, { { Typedef, 8 }, { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "timer_gettime", 2, { Long, 8 }, { { Typedef, 8 }, { Pointer, 8 } } },
		{ "timer_getoverrun", 1, { Long, 8 }, { { Typedef, 8 } } },
		{ "timer_delete", 1, { Long, 8 }, { { Typedef, 8 } } },
		{ "clock_settime", 1, { Long, 8 }, { { Typedef, 4 } } },
		{ "clock_gettime", 1, { Long, 8 }, { { Typedef, 4 } } },
		{ "clock_getres", 2, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 } } },
		{ "clock_nanosleep", 2, { Long, 8 }, { { Typedef, 4 }, { Int, 4 } } },
		{ "exit_group", 1, { Long, 8 }, { { Int, 4 } } },
		{ "epoll_wait", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "epoll_ctl", 4, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Int, 4 }, { Pointer, 8 } } },
		{ "tgkill", 3, { Long, 8 }, { { Typedef, 4 }, { Typedef, 4 }, { Int, 4 } } },
		{ "utimes", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "vserver", 0, { Long, 8 }, { } },
		{ "mbind", 6, { Long, 8 }, { { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { UInt, 4 } } },
		{ "set_mempolicy", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { ULong, 8 } } },
		{ "get_mempolicy", 5, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "mq_open", 4, { Long, 8 }, { { Pointer, 8 }, { Int, 4 }, { Int, 4 }, { Pointer, 8 } } },
		{ "mq_unlink", 1, { Long, 8 }, { { Pointer, 8 } } },
		{ "mq_timedsend", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { UInt, 4 }, { Pointer, 8 } } },
		{ "mq_timedreceive", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "mq_notify", 2, { Long, 8 }, { { Int, 4 }, { Pointer, 8 } } },
		{ "mq_getsetattr", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "kexec_load", 4, { Long, 8 }, { { ULong, 8 }, { ULong, 8 }, { Pointer, 8 }, { ULong, 8 } } },
		{ "waitid", 5, { Long, 8 }, { { Int, 4 }, { Typedef, 4 }, { Pointer, 8 }, { Int, 4 }, { Pointer, 8 } } },
		{ "add_key", 5, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "request_key", 4, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "keyctl", 5, { Long, 8 }, { { Int, 4 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "ioprio_set", 3, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Int, 4 } } },
		{ "ioprio_get", 2, { Long, 8 }, { { Int, 4 }, { Int, 4 } } },
		{ "inotify_init", 0, { Long, 8 }, { } },
		{ "inotify_add_watch", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "inotify_rm_watch", 2, { Long, 8 }, { { Int, 4 }, { Int, 4 } } },
		{ "migrate_pages", 4, { Long, 8 }, { { Typedef, 4 }, { ULong, 8 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "openat", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "mkdirat", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "mknodat", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { UInt, 4 } } },
		{ "fchownat", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Typedef, 4 }, { Typedef, 4 }, { Int, 4 } } },
		{ "futimesat", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "newfstatat", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "unlinkat", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "renameat", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Pointer, 8 } } },
		{ "linkat", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "symlinkat", 3, { Long, 8 }, { { Pointer, 8 }, { Int, 4 }, { Pointer, 8 } } },
		{ "readlinkat", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "fchmodat", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "faccessat", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "pselect6", 6, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "ppoll", 5, { Long, 8 }, { { Pointer, 8 }, { UInt, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "unshare", 1, { Long, 8 }, { { ULong, 8 } } },
		{ "set_robust_list", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "get_robust_list", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "splice", 6, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { UInt, 4 } } },
		{ "tee", 4, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Int, 4 }, { UInt, 4 } } },
		{ "sync_file_range", 4, { Long, 8 }, { { Int, 4 }, { Typedef, 8 }, { Typedef, 8 }, { UInt, 4 } } },
		{ "vmsplice", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { ULong, 8 }, { UInt, 4 } } },
		{ "move_pages", 6, { Long, 8 }, { { Typedef, 4 }, { ULong, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "utimensat", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "epoll_pwait", 6, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "signalfd", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "timerfd_create", 2, { Long, 8 }, { { Int, 4 }, { Int, 4 } } },
		{ "eventfd", 1, { Long, 8 }, { { UInt, 4 } } },
		{ "fallocate", 4, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Typedef, 8 }, { Typedef, 8 } } },
		{ "timerfd_settime", 4, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "timerfd_gettime", 2, { Long, 8 }, { { Int, 4 }, { Pointer, 8 } } },
		{ "accept4", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "signalfd4", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "eventfd2", 2, { Long, 8 }, { { UInt, 4 }, { Int, 4 } } },
		{ "epoll_create1", 1, { Long, 8 }, { { Int, 4 } } },
		{ "dup3", 3, { Long, 8 }, { { UInt, 4 }, { UInt, 4 }, { Int, 4 } } },
		{ "pipe2", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "inotify_init1", 1, { Long, 8 }, { { Int, 4 } } },
		{ "preadv", 5, { Long, 8 }, { { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "pwritev", 5, { Long, 8 }, { { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "rt_tgsigqueueinfo", 4, { Long, 8 }, { { Typedef, 4 }, { Typedef, 4 }, { Int, 4 }, { Pointer, 8 } } },
		{ "perf_event_open", 5, { Long, 8 }, { { Pointer, 8 }, { Typedef, 4 }, { Int, 4 }, { Int, 4 }, { ULong, 8 } } },
		{ "recvmmsg", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 }, { UInt, 4 }, { Pointer, 8 } } },
		{ "fanotify_init", 2, { Long, 8 }, { { UInt, 4 }, { UInt, 4 } } },
		{ "fanotify_mark", 5, { Long, 8 }, { { Int, 4 }, { UInt, 4 }, { Int, 4 }, { Int, 4 }, { Pointer, 8 } } },
		{ "prlimit64", 4, { Long, 8 }, { { Typedef, 4 }, { UInt, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "name_to_handle_at", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "open_by_handle_at", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "clock_adjtime", 2, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 } } },
		{ "syncfs", 1, { Long, 8 }, { { Int, 4 } } },
		{ "sendmmsg", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 }, { UInt, 4 } } },
		{ "setns", 2, { Long, 8 }, { { Int, 4 }, { Int, 4 } } },
		{ "getcpu", 3, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "process_vm_readv", 6, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 }, { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "process_vm_writev", 6, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 }, { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "kcmp", 5, { Long, 8 }, { { Typedef, 4 }, { Typedef, 4 }, { Int, 4 }, { ULong, 8 }, { ULong, 8 } } },
		{ "finit_module", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "sched_setattr", 3, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "sched_getattr", 4, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 }, { UInt, 4 }, { UInt, 4 } } },
		{ "renameat2", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "seccomp", 3, { Long, 8 }, { { UInt, 4 }, { UInt, 4 }, { Pointer, 8 } } },
		{ "getrandom", 3, { Long, 8 }, { { Pointer, 8 }, { Int, 4 }, { UInt, 4 } } },
		{ "memfd_create", 2, { Long, 8 }, { { Pointer, 8 }, { UInt, 4 } } },
		{ "kexec_file_load", 5, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { ULong, 8 }, { Pointer, 8 }, { ULong, 8 } } },
		{ "bpf", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "execveat", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "userfaultfd", 1, { Long, 8 }, { { Int, 4 } } },
		{ "membarrier", 3, { Long, 8 }, { { Int, 4 }, { UInt, 4 }, { Int, 4 } } },
		{ "mlock2", 3, { Long, 8 }, { { ULong, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "copy_file_range", 6, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { UInt, 4 } } },
		{ "preadv2", 6, { Long, 8 }, { { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { Int, 4 } } },
		{ "pwritev2", 6, { Long, 8 }, { { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { Int, 4 } } },
		{ "pkey_mprotect", 4, { Long, 8 }, { { ULong, 8 }, { Int, 4 }, { ULong, 8 }, { Int, 4 } } },
		{ "pkey_alloc", 2, { Long, 8 }, { { ULong, 8 }, { ULong, 8 } } },
		{ "pkey_free", 1, { Long, 8 }, { { Int, 4 } } },
		{ "statx", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 }, { UInt, 4 }, { Pointer, 8 } } },
		{ "io_pgetevents", 6, { Long, 8 }, { { Int, 4 }, { Long, 8 }, { Long, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "rseq", 4, { Long, 8 }, { { Pointer, 8 }, { Int, 4 }, { Int, 4 }, { Int, 4 } } },
		{ "uretprobe", 0, { Long, 8 }, { } },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ "pidfd_send_signal", 4, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "io_uring_setup", 2, { Long, 8 }, { { Int, 4 }, { Pointer, 8 } } },
		{ "io_uring_enter", 6, { Long, 8 }, { { UInt, 4 }, { Int, 4 }, { Int, 4 }, { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "io_uring_register", 4, { Long, 8 }, { { UInt, 4 }, { UInt, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "open_tree", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "move_mount", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "fsopen", 2, { Long, 8 }, { { Pointer, 8 }, { UInt, 4 } } },
		{ "fsconfig", 5, { Long, 8 }, { { Int, 4 }, { UInt, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "fsmount", 3, { Long, 8 }, { { Int, 4 }, { UInt, 4 }, { UInt, 4 } } },
		{ "fspick", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "pidfd_open", 2, { Long, 8 }, { { Typedef, 4 }, { UInt, 4 } } },
		{ "clone3", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "close_range", 3, { Long, 8 }, { { UInt, 4 }, { UInt, 4 }, { UInt, 4 } } },
		{ "openat2", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "pidfd_getfd", 3, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { UInt, 4 } } },
		{ "faccessat2", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "process_madvise", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Int, 4 }, { UInt, 4 } } },
		{ "epoll_pwait2", 6, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "mount_setattr", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "quotactl_fd", 4, { Long, 8 }, { { UInt, 4 }, { UInt, 4 }, { Int, 4 }, { Pointer, 8 } } },
		{ "landlock_create_ruleset", 3, { Long, 8 }, { { Pointer, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "landlock_add_rule", 4, { Long, 8 }, { { Int, 4 }, { Elaborated, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "landlock_restrict_self", 2, { Long, 8 }, { { Int, 4 }, { Int, 4 } } },
		{ "memfd_secret", 1, { Long, 8 }, { { UInt, 4 } } },
		{ "process_mrelease", 2, { Long, 8 }, { { Int, 4 }, { UInt, 4 } } },
		{ "futex_waitv", 5, { Long, 8 }, { { Pointer, 8 }, { UInt, 4 }, { UInt, 4 }, { Pointer, 8 }, { Typedef, 4 } } },
		{ "set_mempolicy_home_node", 4, { Long, 8 }, { { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "cachestat", 4, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "fchmodat2", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { UInt, 4 } } },
		{ "map_shadow_stack", 3, { Long, 8 }, { { ULong, 8 }, { ULong, 8 }, { UInt, 4 } } },
		{ "futex_wake", 4, { Long, 8 }, { { Pointer, 8 }, { ULong, 8 }, { Int, 4 }, { UInt, 4 } } },
		{ "futex_wait", 6, { Long, 8 }, { { Pointer, 8 }, { ULong, 8 }, { ULong, 8 }, { UInt, 4 }, { Pointer, 8 }, { Typedef, 4 } } },
		{ "futex_requeue", 4, { Long, 8 }, { { Pointer, 8 }, { UInt, 4 }, { Int, 4 }, { Int, 4 } } },
		{ "statmount", 4, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Int, 4 }, { UInt, 4 } } },
		{ "listmount", 4, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Int, 4 }, { UInt, 4 } } },
		{ "lsm_get_self_attr", 4, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "lsm_set_self_attr", 4, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 }, { Int, 4 }, { Int, 4 } } },
		{ "lsm_list_modules", 3, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "mseal", 3, { Long, 8 }, { { ULong, 8 }, { Int, 4 }, { ULong, 8 } } },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ },
		{ "rt_sigaction", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "rt_sigreturn", 0, { Long, 8 }, { } },
		{ "ioctl", 3, { Long, 8 }, { { UInt, 4 }, { UInt, 4 }, { ULong, 8 } } },
		{ "readv", 3, { Long, 8 }, { { ULong, 8 }, { Pointer, 8 }, { ULong, 8 } } },
		{ "writev", 3, { Long, 8 }, { { ULong, 8 }, { Pointer, 8 }, { ULong, 8 } } },
		{ "recvfrom", 6, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Int, 4 }, { UInt, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "sendmsg", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "recvmsg", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 } } },
		{ "execve", 3, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "ptrace", 4, { Long, 8 }, { { Long, 8 }, { Long, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "rt_sigpending", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "rt_sigtimedwait", 4, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "rt_sigqueueinfo", 3, { Long, 8 }, { { Typedef, 4 }, { Int, 4 }, { Pointer, 8 } } },
		{ "sigaltstack", 2, { Long, 8 }, { { Pointer, 8 }, { Pointer, 8 } } },
		{ "timer_create", 3, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "mq_notify", 2, { Long, 8 }, { { Int, 4 }, { Pointer, 8 } } },
		{ "kexec_load", 4, { Long, 8 }, { { ULong, 8 }, { ULong, 8 }, { Pointer, 8 }, { ULong, 8 } } },
		{ "waitid", 5, { Long, 8 }, { { Int, 4 }, { Typedef, 4 }, { Pointer, 8 }, { Int, 4 }, { Pointer, 8 } } },
		{ "set_robust_list", 2, { Long, 8 }, { { Pointer, 8 }, { Int, 4 } } },
		{ "get_robust_list", 3, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "vmsplice", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { ULong, 8 }, { UInt, 4 } } },
		{ "move_pages", 6, { Long, 8 }, { { Typedef, 4 }, { ULong, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "preadv", 5, { Long, 8 }, { { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "pwritev", 5, { Long, 8 }, { { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "rt_tgsigqueueinfo", 4, { Long, 8 }, { { Typedef, 4 }, { Typedef, 4 }, { Int, 4 }, { Pointer, 8 } } },
		{ "recvmmsg", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 }, { UInt, 4 }, { Pointer, 8 } } },
		{ "sendmmsg", 4, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { UInt, 4 }, { UInt, 4 } } },
		{ "process_vm_readv", 6, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 }, { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "process_vm_writev", 6, { Long, 8 }, { { Typedef, 4 }, { Pointer, 8 }, { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 } } },
		{ "setsockopt", 5, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Int, 4 }, { Pointer, 8 }, { Int, 4 } } },
		{ "getsockopt", 5, { Long, 8 }, { { Int, 4 }, { Int, 4 }, { Int, 4 }, { Pointer, 8 }, { Pointer, 8 } } },
		{ "io_setup", 2, { Long, 8 }, { { UInt, 4 }, { Pointer, 8 } } },
		{ "io_submit", 3, { Long, 8 }, { { Int, 4 }, { Long, 8 }, { Pointer, 8 } } },
		{ "execveat", 5, { Long, 8 }, { { Int, 4 }, { Pointer, 8 }, { Pointer, 8 }, { Pointer, 8 }, { Int, 4 } } },
		{ "preadv2", 6, { Long, 8 }, { { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { Int, 4 } } },
		{ "pwritev2", 6, { Long, 8 }, { { ULong, 8 }, { Pointer, 8 }, { ULong, 8 }, { ULong, 8 }, { ULong, 8 }, { Int, 4 } } },
