all:
#	$(CC) libclang.c -I /usr/lib/llvm-14/include/ /usr/lib/llvm-14/lib/libclang.so
	$(CC) -g libclang.c -I ~/.capt/root/usr/lib/llvm-15/include/ ~/.capt/root/usr/lib/x86_64-linux-gnu/libclang-15.so

clean:
	$(RM) a.out

fclean: clean
